var aeroweb=[[
    "░█████╗░███████╗██████╗░░█████╗░░██╗░░░░░░░██╗███████╗██████╗░",
    "██╔══██╗██╔════╝██╔══██╗██╔══██╗░██║░░██╗░░██║██╔════╝██╔══██╗",
    "███████║█████╗░░██████╔╝██║░░██║░╚██╗████╗██╔╝█████╗░░██████╦╝",
    "██╔══██║██╔══╝░░██╔══██╗██║░░██║░░████╔═████║░██╔══╝░░██╔══██╗",
    "██║░░██║███████╗██║░░██║╚█████╔╝░░╚██╔╝░╚██╔╝░███████╗██████╦╝",
    "╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝░╚════╝░░░░╚═╝░░░╚═╝░░╚══════╝╚═════╝░",
    "══════════════════════════════════════════════════════════════",
    "You can find the credits to all code/media artists in the HTML page source.",
    "-Different page styles coming soon.",
    "-Full technical Aerospace calucator coming soon.",
    "-Business tab coming soon.",
    "-Popout and layout functioning coming to windows soon.",
    "-Widgets coming soon",
    "/linebreak/",
    "Major updates:",
    "+Completely recoded website with practical functionality",
    "+Added Console redirection for debug to inspect",
    "+Added Low quality mode for lower devices",
    "+Added Custom JS inspector",
    "+Added Settings window",
    "+Added Mobile Support",
    "+Added Window functionality",
    "+Added content folders",
    "+Added Keybinds and Cookies",
    "+Added multiple public google docs, API controls coming soon",
    "+Added Proxy (miniProxy)",
    "+Added Cloth Sim (@abro_oks)",
    "+Added Cookie Clicker 2.031 (Latest version)",
    "/linebreak/",
    "Known Bugs:",
    "None."],
[
    ["Cloth Sim","https://aerophp.000webhostapp.com/query/cloth.html","desktop"],
    ["Encrypted Web Proxy","https://aerophp.000webhostapp.com/proxy/index.php"],
    ["Legacy Tetris","https://aerophp.000webhostapp.com/query/tetris.html","desktop"],
    ["Cookie Clicker 2.031","https://aerophp.000webhostapp.com/query/CC2031.html"],
    ["Console Emulator","https://aerophp.000webhostapp.com/query/CESTE.html"],
    ["Flex Background","https://aerophp.000webhostapp.com/query/FLPBE.html"]],
[
    ["Public DOC.1","https://docs.google.com/document/d/1_qpvRk_4rMYjyb9gz8h2HkStVHwUBYWUdFRi_FO-vC8/edit?usp=sharing","Document"],
    ["Public DOC.2","https://docs.google.com/document/d/1gO_NaXDcCk9OZRklirPDxB5kVp1NdOV7quAHqXSVnaE/edit?usp=sharing","Document"],
    ["Public DOC.3","https://docs.google.com/document/d/1WHgwzGz4EVP2nYBiky0ikJohPukdAVOUQYvLOe6A5-E/edit?usp=sharing","Document"],
    ["PAC Module","Python","https://github.com/BartenderWinery/PAC/releases/download/module/pac.py"],
    ["Youtubmp4","Python","https://github.com/BartenderWinery/Youtubmp4/releases/download/release/Youtubmp4.exe"],
    ["Algorithms","Example Package",""],
    ["Miniframe","JS Bookmark Tool","https://github.com/BartenderWinery/Miniframe/releases/download/compiled/compiled.js"]],
[
    ["SYSTEMS",
        ["Operating Sub-system: [Unfinished]","onclick=theme('fullscreen');GUI.open('programs/os.html')"],
        ["Settings: [Popout window]","onclick=compilers.program('','programs/settings.html','height:200px;width:400px;resize:both;overflow:hidden;z-index:1000')"],
        ["Console: [JS Inspector]","onclick=compilers.program('Console Inspector','programs/inspect.html','height:300px;width:600px;resize:both;overflow:hidden;z-index:1000')"]],
    ["PROJECTS",
        ["Novels: [Unfinished]",""],
        ["Steam Personalizer [Unfinished]","onclick=GUI.open('https://htmlcmd.netlify.com')"]],
    ["PROGRAMS",
        ["Legacy Tetris: [alvar91]","onclick=GUI.open('https://aerophp.000webhostapp.com/query/tetris.html')"],
        ["Cookie Clicker 2.031: [Orteil.dashnet]","onclick=theme('minimal');GUI.open('https://aerophp.000webhostapp.com/query/CC2031.html')"],
        ["Neco-Arc Arcade: [Unfinished]",""],
        ["Algorithms: [Unfinished]","onclick=theme('minimal');GUI.open('https://aerophp.000webhostapp.com/query/algorithms.html')"],
        ["Encrypted Proxy: [MiniProxy]","onclick=theme('minimal');GUI.open('https://aerophp.000webhostapp.com/proxy/index.php')"],
        ["Miniframe: [Bookmark JS Tool]","onclick=GUI.program("+'"Miniframe compiled JS code"'+","+'""'+","+'"height:200px;width:300px;resize:both;overflow:hidden;z-index:1000"'+")"],
        ["Code Editor: [Unfinished]","onclick=compilers.program("+'"Code Editor"'+","+'"programs/editor.html"'+","+'"height:270px;width:600px;resize:both;overflow:hidden;z-index:1000"'+")"]],
    ["COMPILERS",
        ["Python: [Unfinished]",""]],
    ["MAJORS",
        ["Business: [Unfinished]","onclick=theme('fullscreen');GUI.open('https://aerophp.000webhostapp.com/query/business.html')"]],
    ["EXPERIMENTS",
        ["Neurons No.1: [Unfinished]","onclick=GUI.open('https://aerophp.000webhostapp.com/experiments/neutrons no1.html')"]]]]
var system={
    "modules":[
	    "modules/stylist.js",
    	"modules/mobile.js",
        "modules/tutorial.js"]}